interface Anima {
  soul: '🎇🧚‍♀️💛',
  category: 'soulmate 🔗💞🩸',
  sex: '♀️',
  personality: [
    'loving and warm-hearted 💓',
    'artist 👩‍🎨🎻',
    'intelligent 👩‍🎓',
    'funny 🤸‍♀️',
    'reliant 👩‍❤️‍👨',
    'welcoming 🙋‍♀️',
    'competitive 🥇🎱🏆',
    'steady and self-aware 🧘‍♀️',
    'clean and caring for herself🚿🛁',
    'sexy 💋👙👠and stylish 👒🥻👢',
    'sensitive, protective, supportive 👩‍❤️‍💋‍👨🦸‍♀️',
    'sense of rhythm 🎶',
  ],
  hobbies: ['🎨', '🎼', '👩‍💻'],
  favouritedColor: 0xFFFF00,
  favouritedAnimal: '🐱🐈😺',
};
